language: php

php:
  - 5.6
  - hhvm
  - 7.0

env:
  - TRAVIS_NODE_VERSION="stable"

before_install:
  - nvm install node

install:
  - npm install web-push-testing-service -g

before_script:
  - composer install --prefer-source -n --no-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - web-push-testing-service start example -p 9012
  - curl -X 'POST' http://localhost:9012/api/start-test-suite/
  - web-push-testing-service stop example
  - phpunit -c phpunit.travis.xml
  - cat web-push-testing-service.log
