dist: trusty
language: php

sudo: required

 # Downloaded browsers will be cached in selenium-assistant by
 # web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant
    - node_modules            # cache modules too
    - $HOME/.composer/cache   # and composer packages
    - vendor

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
  - TRAVIS_NODE_VERSION="stable"

before_install:
  - nvm install node

install:
  - npm install github:GoogleChromeLabs/web-push-testing-service -g

before_script:
  - composer install --prefer-source -n
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - web-push-testing-service start example -p 9012
  - composer test:unit
  - web-push-testing-service stop example

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - composer test:typing

        - stage: Metrics and quality
          env: CODING_STANDARDS
          script:
              - composer test:syntax

        - stage: Security Check
          env: SECURITY_CHECK
          before_script:
              - wget -c https://get.sensiolabs.org/security-checker.phar
              - chmod +x security-checker.phar
          script:
              - ./security-checker.phar security:check
