os: linux
dist: xenial
language: php

addons:
  chrome: stable
  firefox: latest
  apt:
    update: true
    packages:
      # Ubuntu 16+ does not install this dependency by default.
      - libgconf-2-4
      - chromium-chromedriver

services:
  - xvfb

# Downloaded browsers will be cached in selenium-assistant by
# web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - node_modules
    - vendor

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly

env:
  global:
    - TRAVIS_NODE_VERSION="stable"

before_install:
  - nvm install node

install:
  - npm i -g "https://github.com/GoogleChromeLabs/web-push-testing-service.git#012508983fa5dd3d25d06f0b937f92c33fc71382"
  - composer install --prefer-source -n

script:
  - web-push-testing-service start example -p 9012
  - composer test:unit
  - web-push-testing-service stop example

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - composer test:typing

        - stage: Metrics and quality
          env: CODING_STANDARDS
          script:
              - composer test:syntax

        - stage: Security Check
          env: SECURITY_CHECK
          before_script:
              - wget -c https://get.sensiolabs.org/security-checker.phar
              - chmod +x security-checker.phar
          script:
              - ./security-checker.phar security:check
